Algoritmo "estrutura de controle de decisão"
// Disciplina   : Lógica de programação
// Descrição   : Desvio condicional simples
// Autor(a)    : Lucas Carlos da Silva
// Data atual  : 26/07/2022
Var
v, f : logico


Inicio
v <- verdadeiro
f <- falso


se v então
escreval("condição verdadeira")
senão
escreval("condição falsa")
fimse

se f então
escreval("condição verdadeira")
senao
se não f então
escreval("condição falta")
fimse
fimse


Fimalgoritmo