Algoritmo "somar_dois_numeros"
// Disciplina   : Lógica de programação
// Descrição   : Comandos de entrada e saída de dados
// Autor(a)    : Lucas Carlos da Silva
// Data atual  : 26/07/2022
Var
x, y, z : inteiro


Inicio
escreval("ALGORITMO DE SOMA! INFORME DOIS VALORES PARA QUE SEJAM SOMADOS!")
escreval("Digite o PRIMEIRO número e pressione ENTER: ")
leia(x)
escreval("Digite o SEGUNDO número e pressione ENTER: ")
leia(y)
escreval("")
z <- x + y
escreva(x, " + ", y, " = " , z)

Fimalgoritmo